// Wiring Chrome to bb: the native messaging manifest and its host wrapper.
//
// Chrome only starts a native host that a manifest in the browser's own
// NativeMessagingHosts directory names, and only for the extension ids that
// manifest allows. Installing is therefore two files: a wrapper script bb owns
// and a manifest per installed browser.
import { existsSync } from "node:fs";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Pinned by the public key in the extension manifest, so it never moves. */
export const EXTENSION_ID = "chabhnkncinakogfdckllfckfdegbiji";
export const HOST_NAME = "com.bb.browser";

export interface BrowserTarget {
  name: string;
  /** The browser's profile root; its presence means the browser is installed. */
  supportDir: string;
}

function browserTargets(): BrowserTarget[] {
  const home = homedir();
  if (process.platform === "darwin") {
    const support = join(home, "Library", "Application Support");
    return [
      { name: "Google Chrome", supportDir: join(support, "Google", "Chrome") },
      { name: "Google Chrome Beta", supportDir: join(support, "Google", "Chrome Beta") },
      { name: "Google Chrome Canary", supportDir: join(support, "Google", "Chrome Canary") },
      { name: "Chromium", supportDir: join(support, "Chromium") },
      { name: "Microsoft Edge", supportDir: join(support, "Microsoft Edge") },
      { name: "Brave", supportDir: join(support, "BraveSoftware", "Brave-Browser") },
    ];
  }
  const config = join(home, ".config");
  return [
    { name: "Google Chrome", supportDir: join(config, "google-chrome") },
    { name: "Chromium", supportDir: join(config, "chromium") },
    { name: "Microsoft Edge", supportDir: join(config, "microsoft-edge") },
    { name: "Brave", supportDir: join(config, "BraveSoftware", "Brave-Browser") },
  ];
}

/**
 * The plugin's own directory, which holds `extension/` and `native-host/`.
 * A built plugin loads from `dist/`, so the search walks up to find them.
 */
export function pluginRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 4; depth++) {
    if (existsSync(join(dir, "extension", "manifest.json"))) return dir;
    dir = dirname(dir);
  }
  throw new Error("Could not locate the plugin's extension directory");
}

export const extensionDir = () => join(pluginRoot(), "extension");

export interface InstallPaths {
  /** Stable file naming the live socket; the socket itself moves per load. */
  pointerPath: string;
  wrapperPath: string;
}

export function installPaths(dataDir: string, pluginId: string): InstallPaths {
  const root = join(dataDir, "plugins", pluginId);
  return {
    pointerPath: join(root, "bridge.json"),
    wrapperPath: join(root, "native-host", "bb-browser-host"),
  };
}

export interface InstallResult {
  wrapperPath: string;
  manifests: { browser: string; path: string }[];
  missing: string[];
}

/**
 * Chrome execs the host directly, so the wrapper carries everything the bridge
 * needs: the runtime, the script, and the pointer file naming bb's socket.
 * `ELECTRON_RUN_AS_NODE` makes bb's own binary behave as plain node when bb
 * ships as an Electron app.
 */
export async function install(paths: InstallPaths): Promise<InstallResult> {
  const bridgePath = join(pluginRoot(), "native-host", "bridge.mjs");
  const wrapper = [
    "#!/bin/sh",
    "# bb browser native messaging host. Generated by the bb browser plugin.",
    `ELECTRON_RUN_AS_NODE=1 exec ${quote(process.execPath)} ${quote(bridgePath)} ${quote(paths.pointerPath)}`,
    "",
  ].join("\n");

  await mkdir(dirname(paths.wrapperPath), { recursive: true });
  await writeFile(paths.wrapperPath, wrapper, "utf8");
  await chmod(paths.wrapperPath, 0o755);

  const manifest = {
    name: HOST_NAME,
    description: "bb browser native messaging host",
    path: paths.wrapperPath,
    type: "stdio",
    allowed_origins: [`chrome-extension://${EXTENSION_ID}/`],
  };

  const manifests: { browser: string; path: string }[] = [];
  const missing: string[] = [];
  for (const target of browserTargets()) {
    if (!existsSync(target.supportDir)) {
      missing.push(target.name);
      continue;
    }
    const directory = join(target.supportDir, "NativeMessagingHosts");
    await mkdir(directory, { recursive: true });
    const path = join(directory, `${HOST_NAME}.json`);
    await writeFile(path, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    manifests.push({ browser: target.name, path });
  }
  return { wrapperPath: paths.wrapperPath, manifests, missing };
}

function quote(value: string): string {
  return `"${value.replace(/(["\\$`])/g, "\\$1")}"`;
}
